(define (same a . b)
  (define (recur l)
    (if (null? l)
      '()
      (let ((now (car l)))
        (if (= (remainder now 2) (remainder a 2))
          (cons now (recur (cdr l)))
          (recur (cdr l))))))
  (recur (cons a b)))
